### ISSUE TITLE
Full menu page only shows number of posts set in "Reading" settings.

### ISSUE THREAD

**Issue by briancwelch** [presscodes/maera-restaurant#18]
The restaurant menu currently only shows as many menu items that are set under the WordPress "Reading" settings.  This is unwanted behavior.  We must display **_all**_ menu items on the full menu page, and let the user filter them using jQuery (isotope).

**Comment by briancwelch** [comment]
Fixed the "right way" in b304a8ed9d59488fafe42fd14c8c75b36eab9ddb.

**Comment by aristath** [comment]
:+1:
